name: kostum
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  rename: ^2.0.1
  provider: ^6.0.2
  webview_flutter: ^3.0.2
  cupertino_icons: ^1.0.2
  flutter_launcher_icons: ^0.9.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter_icons:
  android: "launcher_icon"
  ios: false
  image_path: "assets/kostum.png"

flutter:
  uses-material-design: true

  assets:
     - assets/kostum.png
